//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEISURECore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Visiting = new HashSet<Visiting>();
        }
    
        public int ID_Event { get; set; }
        public Nullable<int> ID_Object { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> Attendance { get; set; }
        public string Status { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual Type_Event Type_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visiting> Visiting { get; set; }
    }
}
