//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEISURECore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEISUREEntities : DbContext
    {
        public LEISUREEntities()
            : base("name=LEISUREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Event> Type_Event { get; set; }
        public virtual DbSet<Type_Object> Type_Object { get; set; }
        public virtual DbSet<Visiting> Visiting { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
