//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEISURECore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visiting
    {
        public int ID_OV { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Object { get; set; }
        public Nullable<int> ID_Visitor { get; set; }
        public Nullable<int> ID_Event { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Object Object { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
